---
display-name: Integration Training
description: These integrations can be used for skilling up on the Kinetic Platform and showcase some common integration methods that can be used as a model for building your own!
